//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageSpiderApi.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageTable
    {
        public int Id { get; set; }
        public string Guid { get; set; }
        public string Alt { get; set; }
        public string OriginalUrl { get; set; }
        public string NewUrl { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public int CatalogId { get; set; }
        public string WebSiteUrl { get; set; }
        public Nullable<bool> IsDownLoad { get; set; }
        public Nullable<System.DateTime> DownLoadTime { get; set; }
    
        public virtual CatalogTable CatalogTable { get; set; }
    }
}
